name = "lmsystemv2-api"
main = "workers/api.js"
compatibility_date = "2026-04-22"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "lmsystemv2-db"
database_id = "1de90532-157b-473e-8e7a-655ca9e0953d"

# Produção com domínio próprio (exemplo):
# routes = [
#   { pattern = "app.seudominio.com/api/*", zone_name = "seudominio.com" }
# ]
